version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: industria-db
    environment:
      POSTGRES_DB: industria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - industria-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: industria-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/industria
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/industria
    restart: unless-stopped
    depends_on:
      keycloak:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - industria-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak
    command: start-dev --http-port=8080 --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/industria
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/industria"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - industria-network

  frontend:
    build:
      context: ./Front-End
      dockerfile: Dockerfile
    container_name: industria-frontend
    volumes:
      # Monter le code source
      - ./Front-End:/app
      # Exclure node_modules
      - /app/node_modules
      # Persister les node_modules
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOSTNAME=0.0.0.0
      # Exposed on localhost so the browser can reach the API
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - API_INTERNAL_URL=http://backend:8080
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=supersecretkey123456789
    restart: unless-stopped
    depends_on:
      - backend
    command: sh -c "bun install && bun run dev"
    networks:
      - industria-network


networks:
  industria-network:
    driver: bridge

volumes:
  db_data:
  frontend_node_modules:
